### ISSUE TITLE
Building a Spring Boot project fails - Unknown flag: chown

### ISSUE THREAD

**Issue by cmoulliard** [buildpack/samples#17]
### Issue

The `pack build` command reports the following error `Error: image build: Unknown flag: chown` 
```
pack build --path ./ cmoulliard/snowdrop:v1.0.0.alpha1
2018/11/07 10:07:20 Pulling builder image 'packs/samples' (use --no-pull flag to skip this step)
2018/11/07 10:07:53 Selected run image 'packs/run' from stack 'io.buildpacks.stacks.bionic'
2018/11/07 10:07:53 Pulling run image 'packs/run' (use --no-pull flag to skip this step)
*** DETECTING:
2018/11/07 09:07:59 Group: Sample Node.js Buildpack: fail
2018/11/07 09:07:59 Group: Sample Java Buildpack: pass
*** ANALYZING: Reading information from previous image for possible re-use
2018/11/07 10:07:57 WARNING: skipping analyze, image not found
*** BUILDING:
*** EXPORTING:
---> Java buildpack
---> Installing JDK
Step 1/3 : FROM packs/run
---> 2adf4cd3fc67
Step 2/3 : ADD --chown=1000:1000 /workspace/app /workspace/app
Step 2/3 : ADD --chown=1000:1000 /workspace/app /workspace/app
Error: image build: Unknown flag: chown
```

### Steps to reproduce the error

- Install latest `pack` version -: https://github.com/buildpack/pack/releases/tag/v0.0.5
- Create a simple Spring Boot project locally 
```
curl http://start.spring.io/starter.zip -o demo.zip && unzip demo.zip
```
- Execute the build pack command
```
pack build --path ./ cmoulliard/snowdrop:v1.0.0.alpha1
```

**Comment by cmoulliard** [comment]
As this error is docker's related (I think so), can you then document which docker version it is required to use -> https://forums.docker.com/t/copy-chown-fails-in-automated-build-unknown-flag-chown/43059/3

**Comment by jromero** [comment]
It appears that this error is no longer relevant. Closing it for now.

As for docker version compatibility we specify docker api version `1.38` which is supported by docker engine >= `18.06`. Reference: https://docs.docker.com/develop/sdk/#api-version-matrix

We'll determine where the best place would be to document this specific requirement as it impacts both [pack](https://github.com/buildpack/pack) and [lifecycle](https://github.com/buildpack/lifecycle) but not necessarily the samples.
