### ISSUE TITLE
Sample stacks do not work

### ISSUE THREAD

**Issue by derkoe** [buildpack/samples#42]
When using the sample stacks with pack version 0.4.1 the following error occurs:

```
ERROR: invalid builder 'cnbs/sample-stack-build:alpine': builder index.docker.io/cnbs/sample-stack-build:alpine missing label io.buildpacks.builder.metadata -- try recreating builder
```

seems like the sample builders are missing a newly required label `io.buildpacks.builder.metadata`

**Comment by jromero** [comment]
Seems like you are trying to use a stack as a builder. What configuration/command are you trying to execute?

It should be `cnbs/sample-builder:alpine` for the builder.

**Comment by derkoe** [comment]
Oh - I forgot to create the builder locally. It worked after creating the builder with:

```
 pack create-builder cnbs/sample-builder:alpine --builder-config builders/alpine/builder.toml --no-pull
```

and then using it with `--builder cnbs/sample-builder:alpine`.
