### ISSUE TITLE
[java] question : Is the name pf the java stack appropriate ?

### ISSUE THREAD

**Issue by cmoulliard** [buildpack/samples#7]
[java] question : Is the name of the java stack appropriate ? As the /bin/build script will perform `maven` compile goal, then the name of the image should be `java maven buildpack` ?

**Comment by jromero** [comment]
Thank you for bringing this up. This has been [addressed](https://github.com/buildpack/samples/tree/master/buildpacks/java-maven). 

Many more changes related to this coming (#35).
